# Generated by Django 5.1.4 on 2026-03-23 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الكلية")),
            ],
            options={
                "verbose_name": "الكلية",
                "verbose_name_plural": "الكليات",
            },
        ),
        migrations.RemoveField(
            model_name="profile",
            name="department",
        ),
        migrations.AddField(
            model_name="profile",
            name="department_text",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="القسم (نص)"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "مشرف / أستاذ"),
                    ("assistant", "مراقب / مصحح"),
                    ("student", "طالب"),
                ],
                default="student",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم القسم")),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="accounts.college",
                        verbose_name="الكلية",
                    ),
                ),
            ],
            options={
                "verbose_name": "القسم",
                "verbose_name_plural": "الأقسام",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="academic_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.department",
                verbose_name="القسم الأكاديمي المعتمد",
            ),
        ),
    ]
