# Generated by Django 5.1.4 on 2026-04-03 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_college_remove_profile_department_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="college",
            options={
                "ordering": ["name"],
                "verbose_name": "الكلية",
                "verbose_name_plural": "الكليات",
            },
        ),
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["college__name", "name"],
                "verbose_name": "القسم",
                "verbose_name_plural": "الأقسام",
            },
        ),
        migrations.AddField(
            model_name="college",
            name="code",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="رمز الكلية"
            ),
        ),
        migrations.AddField(
            model_name="college",
            name="description",
            field=models.TextField(blank=True, verbose_name="الوصف"),
        ),
        migrations.AddField(
            model_name="department",
            name="code",
            field=models.CharField(blank=True, max_length=10, verbose_name="رمز القسم"),
        ),
        migrations.AddField(
            model_name="department",
            name="head_of_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="رئيس القسم",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="batch_id",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="معرف الدفعة"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="accounts.college",
                verbose_name="الكلية",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="created_by_admin",
            field=models.BooleanField(
                default=False, verbose_name="أنشئ بواسطة الإدارة"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="generated_password",
            field=models.CharField(
                blank=True,
                help_text="تُحفظ مؤقتاً لغرض الطباعة والتصدير",
                max_length=50,
                verbose_name="كلمة المرور المولّدة",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_active_account",
            field=models.BooleanField(default=True, verbose_name="حساب فعّال"),
        ),
        migrations.AddField(
            model_name="profile",
            name="level",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "المستوى الأول"),
                    (2, "المستوى الثاني"),
                    (3, "المستوى الثالث"),
                    (4, "المستوى الرابع"),
                ],
                null=True,
                verbose_name="المستوى الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="academic_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.department",
                verbose_name="القسم الأكاديمي",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "أستاذ"),
                    ("assistant", "مراقب / مصحح"),
                    ("student", "طالب"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
