# Generated by Django 5.1.4 on 2026-04-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_college_options_alter_department_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="allowed_roles",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="يخزن قائمة بالأدوار المسموحة لهذا المستخدم",
                verbose_name="الصلاحيات المتعددة",
            ),
        ),
    ]
