# Generated by Django 4.2.7 on 2026-06-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_allowed_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="extra_time_percentage",
            field=models.PositiveIntegerField(
                default=0,
                help_text="الوقت الإضافي المخصص للطالب للحالات الخاصة (مثلاً 50 يعني زيادة 50% من وقت الاختبار الأصلي)",
                verbose_name="نسبة الوقت الإضافي (%)",
            ),
        ),
    ]
