# Generated by Django 4.2.13 on 2026-03-06 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="عنوان الاختبار"),
                ),
                ("subject", models.CharField(max_length=100, verbose_name="المادة")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="الوصف / التعليمات"),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=90, verbose_name="المدة (بالدقائق)"
                    ),
                ),
                (
                    "total_marks",
                    models.PositiveIntegerField(
                        default=100, verbose_name="الدرجة الكلية"
                    ),
                ),
                (
                    "pass_mark",
                    models.PositiveIntegerField(default=50, verbose_name="درجة النجاح"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("active", "نشط"),
                            ("closed", "مغلق"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "shuffle_questions",
                    models.BooleanField(
                        default=False, verbose_name="ترتيب عشوائي للأسئلة"
                    ),
                ),
                (
                    "allow_review",
                    models.BooleanField(
                        default=True, verbose_name="السماح بمراجعة الأسئلة"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ البداية"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "اختبار",
                "verbose_name_plural": "الاختبارات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("is_submitted", models.BooleanField(default=False)),
                (
                    "violations_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد المخالفات"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "time_spent_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الوقت المستغرق (ثانية)"
                    ),
                ),
                (
                    "final_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="الدرجة النهائية"
                    ),
                ),
                (
                    "grade",
                    models.CharField(blank=True, max_length=5, verbose_name="التقدير"),
                ),
                (
                    "is_fully_graded",
                    models.BooleanField(default=False, verbose_name="مصحح بالكامل"),
                ),
                (
                    "grader_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات المصحح"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="exams.exam",
                        verbose_name="الاختبار",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "محاولة اختبار",
                "verbose_name_plural": "محاولات الاختبارات",
                "ordering": ["-started_at"],
                "unique_together": {("exam", "student")},
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq_single", "اختيار من متعدد - إجابة واحدة"),
                            ("mcq_multi", "اختيار من متعدد - إجابات متعددة"),
                            ("true_false", "صح أو خطأ"),
                            ("fill_blank", "ملء الفراغ"),
                            ("short_answer", "إجابة قصيرة"),
                            ("essay", "مقالي"),
                            ("matching", "مطابقة"),
                            ("ordering", "ترتيب"),
                        ],
                        max_length=20,
                        verbose_name="نوع السؤال",
                    ),
                ),
                ("text", models.TextField(verbose_name="نص السؤال")),
                (
                    "marks",
                    models.PositiveIntegerField(default=5, verbose_name="الدرجة"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, verbose_name="الشرح / التغذية الراجعة"
                    ),
                ),
                (
                    "tf_answer",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="الإجابة (صح/خطأ)"
                    ),
                ),
                ("rubric", models.TextField(blank=True, verbose_name="معايير التقييم")),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.exam",
                        verbose_name="الاختبار",
                    ),
                ),
            ],
            options={
                "verbose_name": "سؤال",
                "verbose_name_plural": "الأسئلة",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ViolationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("tab_switch", "تحويل التبويب"),
                            ("window_blur", "مغادرة النافذة"),
                            ("copy_attempt", "محاولة نسخ"),
                            ("right_click", "نقر يمين"),
                            ("devtools", "أدوات المطور"),
                            ("fullscreen_exit", "الخروج من الشاشة الكاملة"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.CharField(blank=True, max_length=255)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="exams.examattempt",
                    ),
                ),
            ],
            options={
                "verbose_name": "مخالفة",
                "verbose_name_plural": "المخالفات",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="نص الخيار")),
                ("is_correct", models.BooleanField(default=False, verbose_name="صحيح")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="exams.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "خيار",
                "verbose_name_plural": "الخيارات",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="QuestionBlank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accepted_answer",
                    models.CharField(max_length=255, verbose_name="الإجابة المقبولة"),
                ),
                (
                    "case_sensitive",
                    models.BooleanField(
                        default=False, verbose_name="حساس لحالة الأحرف"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blanks",
                        to="exams.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "إجابة الفراغ",
                "verbose_name_plural": "إجابات الفراغات",
            },
        ),
        migrations.CreateModel(
            name="OrderingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="نص العنصر")),
                (
                    "correct_position",
                    models.PositiveIntegerField(verbose_name="الموضع الصحيح"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="exams.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "عنصر الترتيب",
                "verbose_name_plural": "عناصر الترتيب",
                "ordering": ["correct_position"],
            },
        ),
        migrations.CreateModel(
            name="MatchingPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "left_text",
                    models.CharField(
                        max_length=255, verbose_name="النص الأيسر (المصطلح)"
                    ),
                ),
                (
                    "right_text",
                    models.CharField(
                        max_length=255, verbose_name="النص الأيمن (التعريف)"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs",
                        to="exams.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "زوج المطابقة",
                "verbose_name_plural": "أزواج المطابقة",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="AttemptAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_text",
                    models.TextField(blank=True, verbose_name="نص الإجابة"),
                ),
                (
                    "selected_options",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="الخيارات المحددة"
                    ),
                ),
                (
                    "matching_answer",
                    models.TextField(blank=True, verbose_name="إجابة المطابقة"),
                ),
                (
                    "ordering_answer",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="إجابة الترتيب"
                    ),
                ),
                (
                    "earned_marks",
                    models.FloatField(
                        blank=True, null=True, verbose_name="الدرجة المكتسبة"
                    ),
                ),
                ("is_graded", models.BooleanField(default=False, verbose_name="مصحح")),
                (
                    "grader_comment",
                    models.TextField(blank=True, verbose_name="تعليق المصحح"),
                ),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exams.examattempt",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exams.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "إجابة",
                "verbose_name_plural": "الإجابات",
                "unique_together": {("attempt", "question")},
            },
        ),
    ]
