# Generated by Django 5.1.4 on 2026-03-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="examattempt",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="exam",
            name="max_attempts",
            field=models.PositiveIntegerField(
                default=1, verbose_name="أقصى عدد محاولات"
            ),
        ),
    ]
