# Generated by Django 5.1.4 on 2026-03-23 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_alter_examattempt_unique_together_exam_max_attempts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_exam", "اختبار جديد"),
                            ("result_ready", "نتيجة جاهزة"),
                            ("exam_reminder", "تذكير باختبار"),
                            ("grading_done", "تم التصحيح"),
                        ],
                        default="new_exam",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="العنوان")),
                ("message", models.TextField(blank=True, verbose_name="الرسالة")),
                (
                    "link",
                    models.CharField(blank=True, max_length=500, verbose_name="الرابط"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروءة")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
                "ordering": ["-created_at"],
            },
        ),
    ]
