# Generated by Django 5.1.4 on 2026-03-23 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="assigned_students",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_exams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطلاب المخصصون",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="random_question_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="عدد الأسئلة العشوائية"
            ),
        ),
        migrations.CreateModel(
            name="StudentExamOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extra_attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="محاولات إضافية"
                    ),
                ),
                (
                    "extra_time_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="وقت إضافي (بالدقائق)"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_overrides",
                        to="exams.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "استثناء طالب",
                "verbose_name_plural": "استثناءات الطلاب",
                "unique_together": {("exam", "student")},
            },
        ),
    ]
