# Generated by Django 5.1.4 on 2026-03-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0004_exam_assigned_students_exam_random_question_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="عند التفعيل، سيتم تحويل جميع الزوار لصفحة الصيانة (لا ينطبق على الإدارة).",
                        verbose_name="تفعيل وضع الصيانة",
                    ),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        blank=True,
                        default="بناءً على التحديثات الطارئة، الموقع حاليًا تحت الصيانة. نعتذر عن الإزعاج وسنعود قريباً!",
                        verbose_name="رسالة الصيانة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات النظام",
                "verbose_name_plural": "إعدادات النظام",
            },
        ),
    ]
