# Generated by Django 5.1.4 on 2026-03-23 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_college_remove_profile_department_and_more"),
        ("exams", "0005_sitesettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="subject",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="المادة (اختياري)"
            ),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="اسم المادة / المقرر"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رمز المادة"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="accounts.department",
                        verbose_name="القسم",
                    ),
                ),
            ],
            options={
                "verbose_name": "المادة",
                "verbose_name_plural": "المواد",
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exams",
                to="exams.course",
                verbose_name="المادة الملحقة",
            ),
        ),
    ]
