# Generated by Django 5.1.4 on 2026-03-23 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_alter_exam_subject_course_exam_course"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="code_language",
            field=models.CharField(
                default="python", max_length=20, verbose_name="لغة البرمجة"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="code_template",
            field=models.TextField(blank=True, verbose_name="كود البداية (Template)"),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("mcq_single", "اختيار من متعدد - إجابة واحدة"),
                    ("mcq_multi", "اختيار من متعدد - إجابات متعددة"),
                    ("true_false", "صح أو خطأ"),
                    ("fill_blank", "ملء الفراغ"),
                    ("short_answer", "إجابة قصيرة"),
                    ("essay", "مقالي"),
                    ("matching", "مطابقة"),
                    ("ordering", "ترتيب"),
                    ("code", "سؤال برمجي"),
                ],
                max_length=20,
                verbose_name="نوع السؤال",
            ),
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="الرسالة")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="exams.examattempt",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "رسالة دردشة",
                "verbose_name_plural": "رسائل الدردشة",
                "ordering": ["timestamp"],
            },
        ),
    ]
