# Generated by Django 5.1.4 on 2026-03-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0008_contactmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="violationlog",
            name="violation_type",
            field=models.CharField(
                choices=[
                    ("tab_switch", "تحويل التبويب"),
                    ("window_blur", "مغادرة النافذة"),
                    ("copy_attempt", "محاولة نسخ"),
                    ("right_click", "نقر يمين"),
                    ("devtools", "أدوات المطور"),
                    ("fullscreen_exit", "الخروج من الشاشة الكاملة"),
                    ("high_noise", "رصد ضجيج مرتفع"),
                    ("hardware_off", "إيقاف الكاميرا/الميكروفون"),
                ],
                max_length=30,
            ),
        ),
    ]
