# Generated by Django 5.1.4 on 2026-03-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0010_alter_violationlog_violation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="question_images/",
                verbose_name="صورة مرفقة (اختياري)",
            ),
        ),
    ]
