# Generated by Django 5.1.4 on 2026-03-30 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0011_question_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProctorSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="proctor_snapshots/%Y/%m/%d/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="exams.examattempt",
                    ),
                ),
            ],
            options={
                "verbose_name": "لقطة شاشة مراقبة",
                "verbose_name_plural": "لقطات شاشة المراقبة",
                "ordering": ["-timestamp"],
            },
        ),
    ]
