# Generated by Django 5.1.4 on 2026-03-31 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0012_proctorsnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attemptanswer",
            name="answer_text",
            field=models.TextField(blank=True, verbose_name="النص (مقالي/فراغات)"),
        ),
        migrations.AlterField(
            model_name="attemptanswer",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="exams.examattempt",
                verbose_name="المحاولة",
            ),
        ),
        migrations.AlterField(
            model_name="attemptanswer",
            name="grader_comment",
            field=models.TextField(blank=True, verbose_name="ملاحظات المصحح"),
        ),
        migrations.AlterField(
            model_name="attemptanswer",
            name="is_graded",
            field=models.BooleanField(default=False, verbose_name="تم التصحيح"),
        ),
        migrations.AlterField(
            model_name="attemptanswer",
            name="matching_answer",
            field=models.TextField(blank=True, verbose_name="إجابة المطابقة (JSON)"),
        ),
        migrations.AlterField(
            model_name="attemptanswer",
            name="ordering_answer",
            field=models.TextField(blank=True, verbose_name="إجابة الترتيب"),
        ),
        migrations.AlterField(
            model_name="attemptanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="exams.question",
                verbose_name="السؤال",
            ),
        ),
        migrations.AlterField(
            model_name="attemptanswer",
            name="selected_options",
            field=models.TextField(blank=True, verbose_name="الخيارات المختارة (MCQ)"),
        ),
    ]
