# Generated by Django 5.1.4 on 2026-04-03 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0013_alter_attemptanswer_answer_text_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["department__college__name", "department__name", "name"],
                "verbose_name": "المادة",
                "verbose_name_plural": "المواد",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taught_courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الأستاذ المسؤول",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="مادة فعّالة"),
        ),
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "المستوى الأول"),
                    (2, "المستوى الثاني"),
                    (3, "المستوى الثالث"),
                    (4, "المستوى الرابع"),
                ],
                null=True,
                verbose_name="المستوى الدراسي",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first", "الفصل الأول"),
                    ("second", "الفصل الثاني"),
                    ("summer", "الفصل الصيفي"),
                ],
                max_length=10,
                verbose_name="الفصل الدراسي",
            ),
        ),
    ]
