# Generated by Django 5.1.4 on 2026-04-03 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0014_alter_course_options_course_instructor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="use_course_bank",
            field=models.BooleanField(
                default=False, verbose_name="استخدام بنك أسئلة المادة"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_bank",
                to="exams.course",
                verbose_name="المادة (بنك الأسئلة)",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "سهل"), ("medium", "متوسط"), ("hard", "صعب")],
                default="medium",
                max_length=20,
                verbose_name="مستوى الصعوبة",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="exam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="exams.exam",
                verbose_name="الاختبار",
            ),
        ),
    ]
