# Generated by Django 5.1.4 on 2026-04-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_allowed_roles"),
        ("exams", "0015_exam_use_course_bank_question_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="assigned_colleges",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_exams",
                to="accounts.college",
                verbose_name="الكليات المستهدفة",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="assigned_departments",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_exams",
                to="accounts.department",
                verbose_name="الأقسام المستهدفة",
            ),
        ),
    ]
