# Generated by Django 4.2.7 on 2026-06-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0016_exam_assigned_colleges_exam_assigned_departments"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="is_mock",
            field=models.BooleanField(
                default=False, verbose_name="اختبار تجريبي (للتدريب)"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="require_camera",
            field=models.BooleanField(
                default=False, verbose_name="يتطلب تحقق بالكاميرا"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="require_seb",
            field=models.BooleanField(
                default=False, verbose_name="يتطلب متصفح آمن (SEB)"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="learning_outcome",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="مخرجات التعلم المستهدفة"
            ),
        ),
    ]
