# Generated by Django 4.2.7 on 2026-06-07 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exams", "0017_exam_is_mock_exam_require_camera_exam_require_seb_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="blind_grading",
            field=models.BooleanField(
                default=False, verbose_name="تفعيل التصحيح الأعمى (إخفاء أسماء الطلاب)"
            ),
        ),
        migrations.CreateModel(
            name="GradeAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_mark",
                    models.FloatField(
                        blank=True, null=True, verbose_name="الدرجة السابقة"
                    ),
                ),
                ("new_mark", models.FloatField(verbose_name="الدرجة الجديدة")),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التعديل"
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_audit_logs",
                        to="exams.examattempt",
                        verbose_name="المحاولة",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المُعدِّل",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_audit_logs",
                        to="exams.question",
                        verbose_name="السؤال",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تعديل درجة",
                "verbose_name_plural": "سجلات تعديل الدرجات",
                "ordering": ["-modified_at"],
            },
        ),
    ]
